--------------------------------------------------------------
Begin Slurm Prologue Fri Sep 20 09:22:05 CDT 2024 1726842125
Job ID:		2391806
Username:	l.peiwang
Partition:	tier2_gpu
End Slurm Prologue Fri Sep 20 09:22:05 CDT 2024 1726842125
--------------------------------------------------------------
/home/l.peiwang/liuenv/lib/python3.10/site-packages/nilearn/input_data/__init__.py:23: FutureWarning: The import path 'nilearn.input_data' is deprecated in version 0.9. Importing from 'nilearn.input_data' will be possible at least until release 0.13.0. Please import from 'nilearn.maskers' instead.
  warnings.warn(message, FutureWarning)
2024-09-20 11:09:07.718432: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-20 11:09:09.850406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38212 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:17:00.0, compute capability: 8.0
Number of CN subjects:
263
Number of PCN subjects:
140
Number of MCI subjects:
458
Number of Dementia subjects:
151
lenth of dataset: 
414
Starting fold 1
Traceback (most recent call last):
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/Transformer.py", line 232, in <module>
    best_model = train_model(X, Y, task, modality, info)
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/Transformer.py", line 139, in train_model
    model = create_transformer_model(input_shape=(91, 109, 91), num_classes=2)
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/Transformer.py", line 63, in create_transformer_model
    patch_embedding_model = patch_embedding_layer(input_shape, patch_size, d_model)
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/Transformer.py", line 44, in patch_embedding_layer
    patches = tf.image.extract_patches(
  File "/home/l.peiwang/liuenv/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/l.peiwang/liuenv/lib/python3.10/site-packages/keras/layers/core/tf_op_layer.py", line 107, in handle
    return TFOpLambda(op)(*args, **kwargs)
  File "/home/l.peiwang/liuenv/lib/python3.10/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
ValueError: Exception encountered when calling layer "tf.image.extract_patches" (type TFOpLambda).

Shape must be rank 4 but is rank 5 for '{{node tf.image.extract_patches/ExtractImagePatches}} = ExtractImagePatches[T=DT_FLOAT, ksizes=[1, 16, 16, 16, 1], padding="VALID", rates=[1, 1, 1, 1, 1], strides=[1, 16, 16, 16, 1]](Placeholder)' with input shapes: [1,?,91,109,91].

Call arguments received:
  • images=tf.Tensor(shape=(1, None, 91, 109, 91), dtype=float32)
  • sizes=['1', '16', '16', '16', '1']
  • strides=['1', '16', '16', '16', '1']
  • rates=['1', '1', '1', '1', '1']
  • padding='VALID'
  • name=None
--------------------------------------------------------------
Begin Slurm Epilogue Fri Sep 20 11:09:28 CDT 2024 1726848568
Name                : cd-MRI-trans
User                : l.peiwang
Partition           : tier2_gpu
Nodes               : gpua412
Cores               : 2
State               : COMPLETED
Submit              : 2024-09-20T09:22:01
Start               : 2024-09-20T09:22:05
End                 : 2024-09-20T11:09:26
Reserved Walltime   : 5-10:50:00
Used Walltime       :   01:47:21
Used CPU Time       :   00:03:08
% User (Computation): 96.64%
% System (I/O)      :  3.36%
Mem Reserved        : 500000M
Max Mem Used        : 14.14G (15185088512.0)
Max Disk Write      : 10.24K (10485.76)
Max Disk Read       : 4.55G (4887758766.08)
Max-Mem-Used Node   : gpua412
Max-Disk-Write Node : gpua412
Max-Disk-Read Node  : gpua412
NVIDIA A100-SXM4-40GB
Error: Unable to retrieve job statistics. Return: No data is available.
End Slurm Epilogue Fri Sep 20 11:09:28 CDT 2024 1726848568
--------------------------------------------------------------
