--------------------------------------------------------------
Begin Slurm Prologue Mon Nov  6 11:57:07 CST 2023 1699293427
Job ID:		4172626
Username:	l.peiwang
Partition:	tier2_cpu
End Slurm Prologue Mon Nov  6 11:57:07 CST 2023 1699293427
--------------------------------------------------------------
/home/l.peiwang/.local/lib/python3.10/site-packages/nilearn/input_data/__init__.py:23: FutureWarning: The import path 'nilearn.input_data' is deprecated in version 0.9. Importing from 'nilearn.input_data' will be possible at least until release 0.13.0. Please import from 'nilearn.maskers' instead.
  warnings.warn(message, FutureWarning)
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:182: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:265: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
Number of CN subjects:
263
Number of PCN subjects:
140
Number of MCI subjects:
458
Number of Dementia subjects:
151
lenth of dataset: 
1012
Running outer loop with random state: 30
Traceback (most recent call last):
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/cdm_interpretation_PET.py", line 19, in <module>
    average_single_weights,average_corrected_weights,average_permuted_single_weights,average_permuted_corrected_weights=hyperparameter_tuning_visual_cov_V3(image,label1,[30],5,3,1000)
  File "/ceph/chpc/home/l.peiwang/Modality_Comparison_AD/main.py", line 93, in hyperparameter_tuning_visual_cov_V3
    result = search.fit(K_train, y_train)
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 874, in fit
    self._run_search(evaluate_candidates)
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 1388, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/model_selection/_search.py", line 851, in evaluate_candidates
    _warn_or_raise_about_fit_failures(out, self.error_score)
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 367, in _warn_or_raise_about_fit_failures
    raise ValueError(all_fits_failed_message)
ValueError: 
All the 15 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/svm/_base.py", line 192, in fit
    X, y = self._validate_data(
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/base.py", line 565, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/utils/validation.py", line 1106, in check_X_y
    X = check_array(
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/utils/validation.py", line 921, in check_array
    _assert_all_finite(
  File "/export/anaconda/anaconda3/anaconda3-2023.03/lib/python3.10/site-packages/sklearn/utils/validation.py", line 161, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
SVC does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

--------------------------------------------------------------
Begin Slurm Epilogue Mon Nov  6 12:03:48 CST 2023 1699293828
Name                : cdm
User                : l.peiwang
Partition           : tier2_cpu
Nodes               : highmem02
Cores               : 2
State               : COMPLETED
Submit              : 2023-11-06T11:57:06
Start               : 2023-11-06T11:57:07
End                 : 2023-11-06T12:03:46
Reserved Walltime   : 4-04:50:00
Used Walltime       :   00:06:39
Used CPU Time       :   00:07:31
% User (Computation): 98.23%
% System (I/O)      :  1.77%
Mem Reserved        : 53000M
Max Mem Used        : 3.21G (3443691520.0)
Max Disk Write      : 0.00  (0.0)
Max Disk Read       : 983.04K (1006632.96)
Max-Mem-Used Node   : highmem02
Max-Disk-Write Node : highmem02
Max-Disk-Read Node  : highmem02
End Slurm Epilogue Mon Nov  6 12:03:48 CST 2023 1699293828
--------------------------------------------------------------
